#
# Makefile for the linux pmfs-filesystem routines.
#

obj-$(CONFIG_WINEFS) += winefs.o

winefs-y := bbuild.o balloc.o dir.o file.o inode.o namei.o super.o symlink.o ioctl.o winefs_stats.o journal.o xattr.o xattr_user.o xip.o wprotect.o
